# -*- coding: utf-8 -*-
"""Armas de Almas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bFXHstbf0HCy1VASII1Xnv4Q3q9l6Wb
"""

p = {"forja":False , "arma":""}

at = {1:"Escudo de Madera", 2:15, 3:"Escudo de Hierro", 4:25, 5:"Escudo de Acero", 6:35}
ag = {1:"Daga", 2:15, 3:"Espada", 4:25, 5:"Hacha", 6:35}
aa = {1:"Arco", 2:15, 3:"Ballesta", 4:25, 5:"Rifle", 6:35}

slime={"nombre":"Slime", "vida":1, "ataque":1, "alcance":1, "recompensa":15}
spider={"nombre":"Spider", "vida":2, "ataque":2, "alcance":2, "recompensa":30}
cat={"nombre":"Cat", "vida":3, "ataque":3, "alcance":3, "recompensa":60}
rey_demonio={"nombre":"Rey Demonio", "vida":6, "ataque":6, "alcance":6, "recompensa": "moneda de alma"}

slime_copy=slime.copy()
spider_copy=spider.copy()
cat_copy=cat.copy()
rey_demonio_copy=rey_demonio.copy()

def bienvenida ():
  print("¡Bienvenido a Armas de Almas, tu misión es derrotar al Rey Demonio, consigue almas para ganar poder y hacerte más fuerte!\n")

def nombre_p ():
  p["nombre"]=input("Por favor introduzca el nombre de su personaje: \n")

def clase_p ():
  print(f"\nAhora es momento de elegir la clase de {p["nombre"]}: \n1. Tanque\n2. Guerrero\n3. Arquero")
  si = False
  while si == False:
    num=(input())
    if num == '1':
      p["clase"]="Tanque"
      si=True
    elif num == '2':
      p["clase"]="Guerrero"
      si=True
    elif num == '3':
      p["clase"]="Arquero"
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.")


def estadisticas_p():
  if p["clase"]=="Tanque":
    p["vida"]=2
    p["ataque"]=1
    p["alcance"]=1
  elif p["clase"]=="Guerrero":
    p["vida"]=1
    p["ataque"]=2
    p["alcance"]=1
  elif p["clase"]=="Arquero":
    p["vida"]=1
    p["ataque"]=1
    p["alcance"]=2
  print(f"\n¡Genial! Las estadísticas de {p["nombre"]} ({p['clase']}) son:\nVida: {p["vida"]}\nAtaque: {p["ataque"]}\nAlcance: {p["alcance"]}")

def nuevo_p():
  nombre_p()
  clase_p()
  estadisticas_p()

def regalo_comienzo():
  p["llave"]=""
  p["mdp"]=10
  print(f"\nAl dirigirse al Gremio de Aventureros, a {p['nombre']} le regalan 10 monedas de plata por ser su primera aventura.")

def comienzo():
  bienvenida()
  nuevo_p()
  regalo_comienzo()

def batalla(enemigo):
  print(f"\nLa batalla contra {enemigo["nombre"]} ha empezado, puede realizar dos acciones por turno de cualquier combinación:\n1. Atacar\n2. Alejarse\n3. Acercarse")
  dis=p["alcance"]
  while enemigo["vida"]>0 and p["vida"]>0:
    for i in range(2):
      if enemigo['vida']<=0:
        return
      si=False
      while si == False:
        num=(input())
        if num == '1':
          if dis<=p["alcance"]:
            enemigo["vida"]-=p["ataque"]
            enemigo["vida"] = max(0, enemigo["vida"])
            print(f"\n{p['nombre']} le ha hecho {p["ataque"]} de daño a {enemigo["nombre"]}.\nAhora {enemigo["nombre"]} tiene {enemigo["vida"]} de vida.")
            si=True
          else: print(f"\n{p['nombre']} está demasiado lejos para atacar.")
        elif num == '2':
          dis+=1
          print(f"\n{p['nombre']} se ha alejado de {enemigo['nombre']}.")
          si=True
        elif num == '3':
          dis-=1
          print(f"\n{p["nombre"]} se ha acercado a {enemigo["nombre"]}.")
          si=True
        else: print("\nPor favor introduzca una de las opciones dadas.")
    if enemigo["vida"]>0:
      if enemigo["alcance"]>=dis:
        p["vida"]-=enemigo["ataque"]
        p["vida"] = max(0, p["vida"])
        print(f"\n{enemigo['nombre']} le ha hecho {enemigo['ataque']} de daño a {p['nombre']}.\nAhora {p['nombre']} tiene {p['vida']} de vida.")
      else:
        dis-=1
        print(f"\n{enemigo["nombre"]} se ha acercado a {p["nombre"]}.")

def fin_batalla(enemigo):
  if enemigo["vida"]<=0:
    print(f"\n{p["nombre"]} le ha ganado a {enemigo["nombre"]}.")
  if p["vida"]<=0:
    print(f"\n{p["nombre"]} ha perdido contra {enemigo["nombre"]}.")

def recompensa(enemigo):
  if enemigo["vida"]<=0:
    print(f"\n¡Felicidades! Has recibido {enemigo["recompensa"]} monedas de plata.")
    p["mdp"]+=enemigo["recompensa"]

def reset_enemigo(enemigo):
  global slime
  global spider
  global cat
  global rey_demonio
  if enemigo==slime:
    slime=slime_copy
  elif enemigo==spider:
    spider=spider_copy
  elif enemigo==cat:
    cat=cat_copy
  elif enemigo==rey_demonio:
    rey_demonio=rey_demonio_copy

def reset_llave():
  p['llave']=''

def m_enemigo(e):
  batalla(e)
  fin_batalla(e)
  recompensa(e)
  reset_enemigo(e)
  reset_llave()


def aventura(l):
  if l == "Llave Slime":
    m_enemigo(slime)
  elif l=="Llave Spider":
    m_enemigo(spider)
  elif l=="Llave Cat":
    m_enemigo(cat)
  elif l=="Llave Rey Demonio":
    m_enemigo(rey_demonio)
  else: print("\nNecesita de una llave para entrar a una mazmorra")

def ya_tiene_l(m,d):
  if p["llave"]==m:
    print("\nYa tiene este objeto, elija otro para comprar.")
  elif p["mdp"]>=d:
    p["llave"]=m
    p["mdp"]-=d
    print(f"\nHas comprado {p["llave"]}.")
    return m
  else:
    print("\nLo siento, no tiene suficientes monedas de plata.")
    return


def llaves_tienda():
  print(f"\nTiene {p['mdp']} monedas de plata, elija la llave que desea comprar:\n1. Llave Slime (10 monedas de plata)\n2. Llave Spider (20 monedas de plata)\n3. Llave Cat (40 monedas de plata)\n4. Llave Rey Demonio (100 monedas de plata)")
  si=False
  while si==False:
    num=input()
    if num=="1":
      ya_tiene_l("Llave Slime",10)
      si=True
    elif num=="2":
      ya_tiene_l("Llave Spider",20)
      si=True
    elif num=="3":
      ya_tiene_l("Llave Cat",40)
      si=True
    elif num=="4":
      ya_tiene_l("Llave Rey Demonio",100)
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.")

def txt_tienda_c(c):
  print(f"\nTiene {p['mdp']} monedas de plata, elija el arma que desea comprar:\n")
  if c=="Tanque":
    print("1. Escudo de Madera (15 monedas de plata)\n2. Escudo de Hierro (25 monedas de plata)\n3. Escudo de Acero (35 monedas de plata)")
  elif c=="Guerrero":
    print("1. Daga (15 monedas de plata)\n2. Espada (25 monedas de plata)\n3. Hacha (35 monedas de plata)")
  elif c=="Arquero":
    print("1. Arco (15 monedas de plata)\n2. Ballesta (25 monedas de plata)\n3. Rifle (35 monedas de plata)")

def si_c_armas(c):
  if c=="Tanque":
    return at
  elif c=="Guerrero":
    return ag
  elif c=="Arquero":
    return aa

def ya_tiene_a(l,m,d):
  if l==m:
    print("\nYa tiene este objeto, elija otro para comprar")
  elif p["mdp"]>=d:
    p["arma"]=m
    p["mdp"]-=d
    print(f"\nHas comprado {p["arma"]}.")
    return m
  else:
    print("\nLo siento, no tiene suficientes monedas de plata.")
    return


def armamento_tienda(c,d):
  txt_tienda_c(c)
  si_c_armas(c)
  si=False
  while si==False:
    num=input()
    if num=="1":
      ya_tiene_a(p["arma"],d[1],d[2])
      si=True
    elif num=="2":
      ya_tiene_a(p["arma"],d[3],d[4])
      si=True
    elif num=="3":
      ya_tiene_a(p["arma"],d[5],d[6])
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.")


def tienda():
  print(f"\nTiene {p['mdp']} monedas de plata, ¿Qué desea comprar?\n1. Armamento\n2. Llaves")
  si=False
  while si==False:
    num=input()
    if num=="1":
      d=si_c_armas(p["clase"])
      armamento_tienda(p['clase'],d)
      si=True
    elif num=="2":
      llaves_tienda()
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.")




def forja(c):
  print('')
  #if c=="Tanque":
    #t_forja()
  #elif c=="Guerrero":
    #g_forja()
  #elif c=="Arquero":
    #a_forja()



def menu():
  print("\n¿Qué desea hacer?\n1. Aventura\n2. Tienda\n3. Forja")
  si = False
  while si == False:
    num=(input())
    if num == '1':
      aventura(p["llave"])
      si=True
    elif num == '2':
      tienda()
      si=True
    elif num == '3'and p['forja']== True:
      forja(p["clase"])
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.\n")

def nt():
  if p['vida']<=0:
    print("Nice Try,\n\n              créditos: MATZELGOT.")

comienzo()
while p["vida"]>0:
  menu()
nt()