# -*- coding: utf-8 -*-
"""Armas de Almas 1.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bFXHstbf0HCy1VASII1Xnv4Q3q9l6Wb
"""

p = {"forja":False , "arma":"", "sumarma":0}

at = {"a":["Escudo de Madera",15,1],"b":["Escudo de Hierro",25,2], "c":["Escudo de Acero",35,3]}
ag = {"a":["Daga",15,1],"b":["Espada",25,2], "c":["Hacha",35,3]}
aa = {"a":["Arco",15,1],"b":["Ballesta",25,2], "c":["Rifle",35,3]}

slime={"nombre":"Slime", "vida":1, "ataque":1, "alcance":1, "recompensa":15}
spider={"nombre":"Spider", "vida":2, "ataque":2, "alcance":2, "recompensa":30}
cat={"nombre":"Cat", "vida":3, "ataque":3, "alcance":3, "recompensa":60}
demonio_menor={"nombre":"Demonio Menor", "vida":6, "ataque":6, "alcance":6, "recompensa": 150}

def bienvenida ():
  print("¡Bienvenido a Armas de Almas, tu misión es derrotar al Demonio Menor, consigue almas para ganar poder y hacerte más fuerte!\n")

def nombre_p ():
  p["nombre"]=input("Por favor introduzca el nombre de su personaje: \n")

def clase_p ():
  print(f"\nAhora es momento de elegir la clase de {p["nombre"]}: \n1. Tanque\n2. Guerrero\n3. Arquero")
  si = False
  while si == False:
    num=(input())
    if num == '1':
      p["clase"]="Tanque"
      si=True
    elif num == '2':
      p["clase"]="Guerrero"
      si=True
    elif num == '3':
      p["clase"]="Arquero"
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.")


def estadisticas_p():
  if p["clase"]=="Tanque":
    p["vida"]=2
    p["ataque"]=1
    p["alcance"]=1
  elif p["clase"]=="Guerrero":
    p["vida"]=1
    p["ataque"]=2
    p["alcance"]=1
  elif p["clase"]=="Arquero":
    p["vida"]=1
    p["ataque"]=1
    p["alcance"]=2
  print(f"\n¡Genial! Las estadísticas de {p["nombre"]} ({p['clase']}) son:\nVida: {p["vida"]}\nAtaque: {p["ataque"]}\nAlcance: {p["alcance"]}")

def nuevo_p():
  nombre_p()
  clase_p()
  estadisticas_p()

def regalo_comienzo():
  p["llave"]=""
  p["mdp"]=10
  print(f"\nAl dirigirse al Gremio de Aventureros, a {p['nombre']} le regalan 10 monedas de plata por ser su primera aventura.")

def comienzo():
  bienvenida()
  nuevo_p()
  regalo_comienzo()

def batalla(enemigo):
  d=si_c_armas(p['clase'])
  x=sumar_armas(d)
  print(f"\nLa batalla contra {enemigo["nombre"]} ha empezado, puede realizar dos acciones por turno de cualquier combinación:\n1. Atacar\n2. Alejarse\n3. Acercarse")
  dis=x[2]
  while enemigo["vida"]>0 and x[0]>0:
    for i in range(2):
      if enemigo['vida']<=0:
        return
      si=False
      while si == False:
        num=(input())
        if num == '1':
          if dis<=x[2]:
            enemigo["vida"]-=x[1]
            enemigo["vida"] = max(0, enemigo["vida"])
            print(f"\n{p['nombre']} le ha hecho {x[1]} de daño a {enemigo["nombre"]}.\nAhora {enemigo["nombre"]} tiene {enemigo["vida"]} de vida.")
            si=True
          else: print(f"\n{p['nombre']} está demasiado lejos para atacar.")
        elif num == '2':
          dis+=1
          print(f"\n{p['nombre']} se ha alejado de {enemigo['nombre']}.")
          si=True
        elif num == '3':
          dis-=1
          print(f"\n{p["nombre"]} se ha acercado a {enemigo["nombre"]}.")
          si=True
        else: print("\nPor favor introduzca una de las opciones dadas.")
    if enemigo["vida"]>0:
      if enemigo["alcance"]>=dis:
        x[0]-=enemigo["ataque"]
        x[0] = max(0, x[0])
        print(f"\n{enemigo['nombre']} le ha hecho {enemigo['ataque']} de daño a {p['nombre']}.\nAhora {p['nombre']} tiene {x[0]} de vida.")
      else:
        dis-=1
        print(f"\n{enemigo["nombre"]} se ha acercado a {p["nombre"]}.")

def fin_batalla(enemigo):
  if enemigo["vida"]<=0:
    print(f"\n{p["nombre"]} le ha ganado a {enemigo["nombre"]}.")
  if p["vida"]<=0:
    print(f"\n{p["nombre"]} ha perdido contra {enemigo["nombre"]}.")

def recompensa(enemigo):
  if enemigo["vida"]<=0:
    print(f"\n¡Felicidades! Has recibido {enemigo["recompensa"]} monedas de plata.")
    p["mdp"]+=enemigo["recompensa"]

def reset_llave():
  p['llave']=''

def m_enemigo(e):
  batalla(e)
  fin_batalla(e)
  recompensa(e)
  reset_llave()


def aventura(l):
  if l == "Llave Slime":
    m_enemigo(slime.copy())
  elif l=="Llave Spider":
    m_enemigo(spider.copy())
  elif l=="Llave Cat":
    m_enemigo(cat.copy())
  elif l=="Llave Demonio Menor":
    m_enemigo(demonio_menor.copy())
  else: print("\nNecesita de una llave para entrar a una mazmorra")

def ya_tiene_l(m,d):
  if p["llave"]==m:
    print("\nYa tiene este objeto, elija otro para comprar.")
  elif p["mdp"]>=d:
    p["llave"]=m
    p["mdp"]-=d
    print(f"\nHas comprado {p["llave"]}.")
    return m
  else:
    print("\nLo siento, no tiene suficientes monedas de plata.")
    return


def llaves_tienda():
  print(f"\nTiene {p['mdp']} monedas de plata, elija la llave que desea comprar:\n1. Llave Slime (10 monedas de plata)\n2. Llave Spider (20 monedas de plata)\n3. Llave Cat (40 monedas de plata)\n4. Llave Demonio Menor (100 monedas de plata)")
  si=False
  while si==False:
    num=input()
    if num=="1":
      ya_tiene_l("Llave Slime",10)
      si=True
    elif num=="2":
      ya_tiene_l("Llave Spider",20)
      si=True
    elif num=="3":
      ya_tiene_l("Llave Cat",40)
      si=True
    elif num=="4":
      ya_tiene_l("Llave Demonio Menor",100)
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.")

def txt_tienda_c(c):
  print(f"\nTiene {p['mdp']} monedas de plata, elija el arma que desea comprar:\n")
  if c=="Tanque":
    print("1. Escudo de Madera (15 monedas de plata)\n2. Escudo de Hierro (25 monedas de plata)\n3. Escudo de Acero (35 monedas de plata)")
  elif c=="Guerrero":
    print("1. Daga (15 monedas de plata)\n2. Espada (25 monedas de plata)\n3. Hacha (35 monedas de plata)")
  elif c=="Arquero":
    print("1. Arco (15 monedas de plata)\n2. Ballesta (25 monedas de plata)\n3. Rifle (35 monedas de plata)")

def si_c_armas(c):
  if c=="Tanque":
    return at
  elif c=="Guerrero":
    return ag
  elif c=="Arquero":
    return aa

def sumar_armas(d):
    if d==at:
        x=p['vida']+p["sumarma"]
        return [x,p['ataque'],p['alcance']]
    elif d==ag:
        x=p['ataque']+p["sumarma"]
        return [p['vida'],x,p['alcance']]
    elif d==aa:
        x=p['alcance']+p["sumarma"]
        return [p['vida'],p['ataque'],x]


def ya_tiene_a(a,n,pr,s):
  if a==n:
    print("\nYa tiene este objeto, elija otro para comprar")
  elif p["mdp"]>=pr:
    p["arma"]=n
    p["sumarma"]=s
    p["mdp"]-=pr
    print(f"\nHas comprado {p["arma"]}.")

  else:
    print("\nLo siento, no tiene suficientes monedas de plata.")


def armamento_tienda(c,d):
  txt_tienda_c(c)
  si=False
  while si==False:
    num=input()
    if num=="1":
      ya_tiene_a(p["arma"],d['a'][0],d['a'][1],d['a'][2])
      si=True
    elif num=="2":
      ya_tiene_a(p["arma"],d['b'][0],d['b'][1],d['b'][2])
      si=True
    elif num=="3":
      ya_tiene_a(p["arma"],d['c'][0],d['c'][1],d['c'][2])
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.")


def tienda():
  print(f"\nTiene {p['mdp']} monedas de plata, ¿Qué desea comprar?\n1. Armamento\n2. Llaves")
  si=False
  while si==False:
    num=input()
    if num=="1":
      d=si_c_armas(p["clase"])
      armamento_tienda(p['clase'],d)
      si=True
    elif num=="2":
      llaves_tienda()
      si=True
    else: print("\nPor favor introduzca una de las opciones dadas.")




def forja(c):
  print('')
  #if c=="Tanque":
    #t_forja()
  #elif c=="Guerrero":
    #g_forja()
  #elif c=="Arquero":
    #a_forja()



def menu():
  if p["mdp"]<10 and p["llave"]=='':
    return
  print("\n¿Qué desea hacer?\n1. Aventura\n2. Tienda\n3. Forja")
  si = False
  while si == False:
    num=(input())
    if num == '1':
      aventura(p["llave"])
      si=True
    elif num == '2':
      tienda()
      si=True
    elif num == '3':
      if p['forja']== True:
        forja(p["clase"])
        si=True
      else:
        print(f"\nTodavía no ha desbloqueado la forja, vuelva a intentarlo después de conseguir su primer alma.")
    else: print("\nPor favor introduzca una de las opciones dadas.\n")

def nt():
    print(f"\n{p['nombre']} ha muerto o se quedó sin dinero para llaves.\nNice Try,\n\n              créditos: MATZELGOT.")

comienzo()
while p["vida"]>0 and (p["mdp"]>=10 or p["llave"]!=''):
  menu()
nt()